### ISSUE TITLE
Wrong Hyperlink in Wallet

### ISSUE THREAD

**Issue by moohooooo** [wanchain/wan-wallet-desktop#32]
![image](https://user-images.githubusercontent.com/128964/74086402-0d3f2700-4ab5-11ea-9a4b-db2600b64eb5.png)

This should be link to https://www.wanscan.org/block/4171076
not https://explorer.wanchain.org/block/4171076

**Comment by pkguowu** [comment]
The wallet you tested is the full node wallet, right?

**Comment by moohooooo** [comment]
Yes Full node

**Comment by pkguowu** [comment]
The full node wallet won't be maintained. Thanks.
