### ISSUE TITLE
Wan Wallet stuck at 99.9% on MacOS

### ISSUE THREAD

**Issue by plisieck** [wanchain/wan-wallet-desktop#37]
What I tried :
-Restart the Wallet
-Restart the computer
-Reinstall the Wallet
-Delete the ~/Library/Wanchain repository

None of this solved the problem.

<img width="944" alt="Capture d’écran 2020-04-14 à 02 35 52" src="https://user-images.githubusercontent.com/12189038/79173926-55eac780-7df9-11ea-8b94-f6caf44a6aa6.png">

**Comment by pkguowu** [comment]
Open data folder and delete config.json
![image](https://user-images.githubusercontent.com/34729163/79200014-65edc000-7e68-11ea-830f-7ba8e38e9dbd.png)

**Comment by plisieck** [comment]
It worked for me,
Thanks !
