### ISSUE TITLE
Unable to send imported wallet contents to another wallet

### ISSUE THREAD

**Issue by OverZealous** [wanchain/wan-wallet-desktop#50]
I'm trying to move the contents of my imported wallet (from WanWalletGUI) into my new wallet using WanWallet for Mac. I imported the old data from the keystore, and I can see the imported wallet contents and balance in the app. I've also tried re-importing the old wallet.

When I try to send from one address to the other (both are within the same app), I get "Failed to Send Transaction".

The logs only say:

```
Failed to send transaction: Cannot read property 'indexOf' of undefined
```

I see the same text within the Developer Tools, and there's no additional context. I get the same error trying to transfer to a different wallet.

I downloaded the app directly from https://www.wanchain.org/getstarted/ and verified the contents. Is there something else I should check?

**Comment by Gabriel-2010** [comment]
I just tried in the same way and it worked. Could you please go to telegram group @WanchainSupport to get help? We need more informations to help you.

**Comment by OverZealous** [comment]
I ended up being able to transfer it using the mywanwallet.io website. I no longer need this fixed.
